// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.ModelsRequests.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.ModelsRequests
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\fine_tuning\models
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ModelsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Mistral.OpenApiClient.v1.fine_tuning.modelsRequests.item collection</summary>
        /// <param name="position">The ID of the model to update.</param>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.ModelsRequests.Item.WithModel_ItemRequestBuilder"/></returns>
        public global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.ModelsRequests.Item.WithModel_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("model_id", position);
                return new global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.ModelsRequests.Item.WithModel_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.ModelsRequests.ModelsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ModelsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/fine_tuning/models", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.ModelsRequests.ModelsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ModelsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/fine_tuning/models", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
