// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AgentCreationRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Completion arguments that will be used to generate assistant responses. Can be overridden at each message request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs? CompletionArgs { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs CompletionArgs { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_description? Description { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_description Description { get; set; }
#endif
        /// <summary>The guardrails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Mistral.OpenApiClient.Models.GuardrailConfig>? Guardrails { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Mistral.OpenApiClient.Models.GuardrailConfig> Guardrails { get; set; }
#endif
        /// <summary>The handoffs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_handoffs? Handoffs { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_handoffs Handoffs { get; set; }
#endif
        /// <summary>Instruction prompt the model will follow during the conversation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_instructions? Instructions { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_instructions Instructions { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.MetadataDict? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.MetadataDict Metadata { get; set; }
#endif
        /// <summary>The model property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>List of tools which are available to the model during the conversation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_tools>? Tools { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_tools> Tools { get; set; }
#endif
        /// <summary>The version_message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_version_message? VersionMessage { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_version_message VersionMessage { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completion_args", n => { CompletionArgs = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs>(global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_description>(global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_description.CreateFromDiscriminatorValue); } },
                { "guardrails", n => { Guardrails = n.GetCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.GuardrailConfig>(global::Soenneker.Mistral.OpenApiClient.Models.GuardrailConfig.CreateFromDiscriminatorValue)?.AsList(); } },
                { "handoffs", n => { Handoffs = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_handoffs>(global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_handoffs.CreateFromDiscriminatorValue); } },
                { "instructions", n => { Instructions = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_instructions>(global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_instructions.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.MetadataDict>(global::Soenneker.Mistral.OpenApiClient.Models.MetadataDict.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "tools", n => { Tools = n.GetCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_tools>(global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_tools.CreateFromDiscriminatorValue)?.AsList(); } },
                { "version_message", n => { VersionMessage = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_version_message>(global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_version_message.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs>("completion_args", CompletionArgs);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_description>("description", Description);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.GuardrailConfig>("guardrails", Guardrails);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_handoffs>("handoffs", Handoffs);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_instructions>("instructions", Instructions);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.MetadataDict>("metadata", Metadata);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_tools>("tools", Tools);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_version_message>("version_message", VersionMessage);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_descriptionMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AgentCreationRequest_description : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_descriptionMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_descriptionMember1? AgentCreationRequestDescriptionMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_descriptionMember1 AgentCreationRequestDescriptionMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_description"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_description CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_description();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AgentCreationRequestDescriptionMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_descriptionMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AgentCreationRequestDescriptionMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AgentCreationRequestDescriptionMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_descriptionMember1>(null, AgentCreationRequestDescriptionMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_handoffsMember1"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AgentCreationRequest_handoffs : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_handoffsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_handoffsMember1? AgentCreationRequestHandoffsMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_handoffsMember1 AgentCreationRequestHandoffsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_handoffs"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_handoffs CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_handoffs();
                if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AgentCreationRequestHandoffsMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_handoffsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AgentCreationRequestHandoffsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AgentCreationRequestHandoffsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_handoffsMember1>(null, AgentCreationRequestHandoffsMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_instructionsMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AgentCreationRequest_instructions : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_instructionsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_instructionsMember1? AgentCreationRequestInstructionsMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_instructionsMember1 AgentCreationRequestInstructionsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_instructions"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_instructions CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_instructions();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AgentCreationRequestInstructionsMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_instructionsMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AgentCreationRequestInstructionsMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AgentCreationRequestInstructionsMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_instructionsMember1>(null, AgentCreationRequestInstructionsMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CodeInterpreterTool"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomConnector"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.DocumentLibraryTool"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.FunctionTool"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ImageGenerationTool"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WebSearchPremiumTool"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WebSearchTool"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AgentCreationRequest_tools : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CodeInterpreterTool"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CodeInterpreterTool? CodeInterpreterTool { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CodeInterpreterTool CodeInterpreterTool { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomConnector"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomConnector? CustomConnector { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomConnector CustomConnector { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.DocumentLibraryTool"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.DocumentLibraryTool? DocumentLibraryTool { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.DocumentLibraryTool DocumentLibraryTool { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.FunctionTool"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.FunctionTool? FunctionTool { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.FunctionTool FunctionTool { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ImageGenerationTool"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.ImageGenerationTool? ImageGenerationTool { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.ImageGenerationTool ImageGenerationTool { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WebSearchPremiumTool"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.WebSearchPremiumTool? WebSearchPremiumTool { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.WebSearchPremiumTool WebSearchPremiumTool { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WebSearchTool"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.WebSearchTool? WebSearchTool { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.WebSearchTool WebSearchTool { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_tools"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_tools CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_tools();
                if("code_interpreter".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CodeInterpreterTool = new global::Soenneker.Mistral.OpenApiClient.Models.CodeInterpreterTool();
                }
                else if("connector".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CustomConnector = new global::Soenneker.Mistral.OpenApiClient.Models.CustomConnector();
                }
                else if("document_library".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.DocumentLibraryTool = new global::Soenneker.Mistral.OpenApiClient.Models.DocumentLibraryTool();
                }
                else if("function".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.FunctionTool = new global::Soenneker.Mistral.OpenApiClient.Models.FunctionTool();
                }
                else if("image_generation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ImageGenerationTool = new global::Soenneker.Mistral.OpenApiClient.Models.ImageGenerationTool();
                }
                else if("web_search_premium".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WebSearchPremiumTool = new global::Soenneker.Mistral.OpenApiClient.Models.WebSearchPremiumTool();
                }
                else if("web_search".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WebSearchTool = new global::Soenneker.Mistral.OpenApiClient.Models.WebSearchTool();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CodeInterpreterTool != null)
                {
                    return CodeInterpreterTool.GetFieldDeserializers();
                }
                else if(CustomConnector != null)
                {
                    return CustomConnector.GetFieldDeserializers();
                }
                else if(DocumentLibraryTool != null)
                {
                    return DocumentLibraryTool.GetFieldDeserializers();
                }
                else if(FunctionTool != null)
                {
                    return FunctionTool.GetFieldDeserializers();
                }
                else if(ImageGenerationTool != null)
                {
                    return ImageGenerationTool.GetFieldDeserializers();
                }
                else if(WebSearchPremiumTool != null)
                {
                    return WebSearchPremiumTool.GetFieldDeserializers();
                }
                else if(WebSearchTool != null)
                {
                    return WebSearchTool.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CodeInterpreterTool != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CodeInterpreterTool>(null, CodeInterpreterTool);
                }
                else if(CustomConnector != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CustomConnector>(null, CustomConnector);
                }
                else if(DocumentLibraryTool != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.DocumentLibraryTool>(null, DocumentLibraryTool);
                }
                else if(FunctionTool != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.FunctionTool>(null, FunctionTool);
                }
                else if(ImageGenerationTool != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ImageGenerationTool>(null, ImageGenerationTool);
                }
                else if(WebSearchPremiumTool != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.WebSearchPremiumTool>(null, WebSearchPremiumTool);
                }
                else if(WebSearchTool != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.WebSearchTool>(null, WebSearchTool);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_version_messageMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AgentCreationRequest_version_message : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_version_messageMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_version_messageMember1? AgentCreationRequestVersionMessageMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_version_messageMember1 AgentCreationRequestVersionMessageMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_version_message"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_version_message CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest.AgentCreationRequest_version_message();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AgentCreationRequestVersionMessageMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_version_messageMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AgentCreationRequestVersionMessageMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AgentCreationRequestVersionMessageMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.AgentCreationRequest_version_messageMember1>(null, AgentCreationRequestVersionMessageMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
