// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BaseModelCard : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aliases property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Aliases { get; set; }
#nullable restore
#else
        public List<string> Aliases { get; set; }
#endif
        /// <summary>The capabilities property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ModelCapabilities? Capabilities { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ModelCapabilities Capabilities { get; set; }
#endif
        /// <summary>The created property</summary>
        public int? Created { get; set; }
        /// <summary>The default_model_temperature property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_default_model_temperature? DefaultModelTemperature { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_default_model_temperature DefaultModelTemperature { get; set; }
#endif
        /// <summary>The deprecation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation? Deprecation { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation Deprecation { get; set; }
#endif
        /// <summary>The deprecation_replacement_model property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation_replacement_model? DeprecationReplacementModel { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation_replacement_model DeprecationReplacementModel { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_description? Description { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_description Description { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The max_context_length property</summary>
        public int? MaxContextLength { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_name? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_name Name { get; set; }
#endif
        /// <summary>The object property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Object { get; set; }
#nullable restore
#else
        public string Object { get; set; }
#endif
        /// <summary>The owned_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnedBy { get; set; }
#nullable restore
#else
        public string OwnedBy { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard"/> and sets the default values.
        /// </summary>
        public BaseModelCard()
        {
            AdditionalData = new Dictionary<string, object>();
            Object = "model";
            OwnedBy = "mistralai";
            Type = "base";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aliases", n => { Aliases = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "capabilities", n => { Capabilities = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ModelCapabilities>(global::Soenneker.Mistral.OpenApiClient.Models.ModelCapabilities.CreateFromDiscriminatorValue); } },
                { "created", n => { Created = n.GetIntValue(); } },
                { "default_model_temperature", n => { DefaultModelTemperature = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_default_model_temperature>(global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_default_model_temperature.CreateFromDiscriminatorValue); } },
                { "deprecation", n => { Deprecation = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation>(global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation.CreateFromDiscriminatorValue); } },
                { "deprecation_replacement_model", n => { DeprecationReplacementModel = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation_replacement_model>(global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation_replacement_model.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_description>(global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_description.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "max_context_length", n => { MaxContextLength = n.GetIntValue(); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_name>(global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_name.CreateFromDiscriminatorValue); } },
                { "object", n => { Object = n.GetStringValue(); } },
                { "owned_by", n => { OwnedBy = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("aliases", Aliases);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ModelCapabilities>("capabilities", Capabilities);
            writer.WriteIntValue("created", Created);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_default_model_temperature>("default_model_temperature", DefaultModelTemperature);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation>("deprecation", Deprecation);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation_replacement_model>("deprecation_replacement_model", DeprecationReplacementModel);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_description>("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteIntValue("max_context_length", MaxContextLength);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_name>("name", Name);
            writer.WriteStringValue("object", Object);
            writer.WriteStringValue("owned_by", OwnedBy);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_default_model_temperatureMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BaseModelCard_default_model_temperature : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_default_model_temperatureMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_default_model_temperatureMember1? BaseModelCardDefaultModelTemperatureMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_default_model_temperatureMember1 BaseModelCardDefaultModelTemperatureMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_default_model_temperature"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_default_model_temperature CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_default_model_temperature();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else {
                    result.BaseModelCardDefaultModelTemperatureMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_default_model_temperatureMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BaseModelCardDefaultModelTemperatureMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BaseModelCardDefaultModelTemperatureMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_default_model_temperatureMember1>(null, BaseModelCardDefaultModelTemperatureMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_deprecationMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BaseModelCard_deprecation : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_deprecationMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_deprecationMember1? BaseModelCardDeprecationMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_deprecationMember1 BaseModelCardDeprecationMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.BaseModelCardDeprecationMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_deprecationMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BaseModelCardDeprecationMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BaseModelCardDeprecationMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_deprecationMember1>(null, BaseModelCardDeprecationMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_deprecation_replacement_modelMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BaseModelCard_deprecation_replacement_model : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_deprecation_replacement_modelMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_deprecation_replacement_modelMember1? BaseModelCardDeprecationReplacementModelMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_deprecation_replacement_modelMember1 BaseModelCardDeprecationReplacementModelMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation_replacement_model"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation_replacement_model CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_deprecation_replacement_model();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.BaseModelCardDeprecationReplacementModelMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_deprecation_replacement_modelMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BaseModelCardDeprecationReplacementModelMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BaseModelCardDeprecationReplacementModelMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_deprecation_replacement_modelMember1>(null, BaseModelCardDeprecationReplacementModelMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_descriptionMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BaseModelCard_description : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_descriptionMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_descriptionMember1? BaseModelCardDescriptionMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_descriptionMember1 BaseModelCardDescriptionMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_description"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_description CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_description();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.BaseModelCardDescriptionMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_descriptionMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BaseModelCardDescriptionMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BaseModelCardDescriptionMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_descriptionMember1>(null, BaseModelCardDescriptionMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_nameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BaseModelCard_name : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_nameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_nameMember1? BaseModelCardNameMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_nameMember1 BaseModelCardNameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_name"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_name CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard.BaseModelCard_name();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.BaseModelCardNameMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_nameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(BaseModelCardNameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(BaseModelCardNameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.BaseModelCard_nameMember1>(null, BaseModelCardNameMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
