// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ClassifierDetailedJobOutMetadata : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cost property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutCost? Cost { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutCost Cost { get; set; }
#endif
        /// <summary>The cost_currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutCostCurrency? CostCurrency { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutCostCurrency CostCurrency { get; set; }
#endif
        /// <summary>The data_tokens property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutDataTokens? DataTokens { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutDataTokens DataTokens { get; set; }
#endif
        /// <summary>The estimated_start_time property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutEstimatedStartTime? EstimatedStartTime { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutEstimatedStartTime EstimatedStartTime { get; set; }
#endif
        /// <summary>The expected_duration_seconds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutExpectedDurationSeconds? ExpectedDurationSeconds { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutExpectedDurationSeconds ExpectedDurationSeconds { get; set; }
#endif
        /// <summary>The train_tokens property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutTrainTokens? TrainTokens { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutTrainTokens TrainTokens { get; set; }
#endif
        /// <summary>The train_tokens_per_step property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutTrainTokensPerStep? TrainTokensPerStep { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutTrainTokensPerStep TrainTokensPerStep { get; set; }
#endif
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ClassifierDetailedJobOutMetadata"/> and sets the default values.
        /// </summary>
        public ClassifierDetailedJobOutMetadata()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ClassifierDetailedJobOutMetadata"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.ClassifierDetailedJobOutMetadata CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.ClassifierDetailedJobOutMetadata();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cost", n => { Cost = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutCost>(global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutCost.CreateFromDiscriminatorValue); } },
                { "cost_currency", n => { CostCurrency = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutCostCurrency>(global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutCostCurrency.CreateFromDiscriminatorValue); } },
                { "data_tokens", n => { DataTokens = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutDataTokens>(global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutDataTokens.CreateFromDiscriminatorValue); } },
                { "estimated_start_time", n => { EstimatedStartTime = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutEstimatedStartTime>(global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutEstimatedStartTime.CreateFromDiscriminatorValue); } },
                { "expected_duration_seconds", n => { ExpectedDurationSeconds = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutExpectedDurationSeconds>(global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutExpectedDurationSeconds.CreateFromDiscriminatorValue); } },
                { "train_tokens", n => { TrainTokens = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutTrainTokens>(global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutTrainTokens.CreateFromDiscriminatorValue); } },
                { "train_tokens_per_step", n => { TrainTokensPerStep = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutTrainTokensPerStep>(global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutTrainTokensPerStep.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutCost>("cost", Cost);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutCostCurrency>("cost_currency", CostCurrency);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutDataTokens>("data_tokens", DataTokens);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutEstimatedStartTime>("estimated_start_time", EstimatedStartTime);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutExpectedDurationSeconds>("expected_duration_seconds", ExpectedDurationSeconds);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutTrainTokens>("train_tokens", TrainTokens);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.JobMetadataOutTrainTokensPerStep>("train_tokens_per_step", TrainTokensPerStep);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
