// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CodeInterpreterToolType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "code_interpreter")]
        #pragma warning disable CS1591
        CodeInterpreter,
        #pragma warning restore CS1591
    }
}
