// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    /// <summary>
    /// Completion arguments that will be used to generate assistant responses. Can be overridden at each message request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompletionArgs : IParsable
    {
        /// <summary>The frequency_penalty property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_frequency_penalty? FrequencyPenalty { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_frequency_penalty FrequencyPenalty { get; set; }
#endif
        /// <summary>The max_tokens property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_max_tokens? MaxTokens { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_max_tokens MaxTokens { get; set; }
#endif
        /// <summary>The prediction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.Prediction? Prediction { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.Prediction Prediction { get; set; }
#endif
        /// <summary>The presence_penalty property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_presence_penalty? PresencePenalty { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_presence_penalty PresencePenalty { get; set; }
#endif
        /// <summary>The random_seed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_random_seed? RandomSeed { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_random_seed RandomSeed { get; set; }
#endif
        /// <summary>Controls the reasoning effort level for reasoning models. &quot;high&quot; enables comprehensive reasoning traces, &quot;none&quot; disables reasoning effort.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_reasoning_effort? ReasoningEffort { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_reasoning_effort ReasoningEffort { get; set; }
#endif
        /// <summary>The response_format property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ResponseFormat? ResponseFormat { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ResponseFormat ResponseFormat { get; set; }
#endif
        /// <summary>The stop property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgsStop? Stop { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgsStop Stop { get; set; }
#endif
        /// <summary>The temperature property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_temperature? Temperature { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_temperature Temperature { get; set; }
#endif
        /// <summary>The tool_choice property</summary>
        public global::Soenneker.Mistral.OpenApiClient.Models.ToolChoiceEnum? ToolChoice { get; set; }
        /// <summary>The top_p property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_top_p? TopP { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_top_p TopP { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs"/> and sets the default values.
        /// </summary>
        public CompletionArgs()
        {
            ToolChoice = global::Soenneker.Mistral.OpenApiClient.Models.ToolChoiceEnum.Auto;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "frequency_penalty", n => { FrequencyPenalty = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_frequency_penalty>(global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_frequency_penalty.CreateFromDiscriminatorValue); } },
                { "max_tokens", n => { MaxTokens = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_max_tokens>(global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_max_tokens.CreateFromDiscriminatorValue); } },
                { "prediction", n => { Prediction = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.Prediction>(global::Soenneker.Mistral.OpenApiClient.Models.Prediction.CreateFromDiscriminatorValue); } },
                { "presence_penalty", n => { PresencePenalty = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_presence_penalty>(global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_presence_penalty.CreateFromDiscriminatorValue); } },
                { "random_seed", n => { RandomSeed = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_random_seed>(global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_random_seed.CreateFromDiscriminatorValue); } },
                { "reasoning_effort", n => { ReasoningEffort = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_reasoning_effort>(global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_reasoning_effort.CreateFromDiscriminatorValue); } },
                { "response_format", n => { ResponseFormat = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ResponseFormat>(global::Soenneker.Mistral.OpenApiClient.Models.ResponseFormat.CreateFromDiscriminatorValue); } },
                { "stop", n => { Stop = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgsStop>(global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgsStop.CreateFromDiscriminatorValue); } },
                { "temperature", n => { Temperature = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_temperature>(global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_temperature.CreateFromDiscriminatorValue); } },
                { "tool_choice", n => { ToolChoice = n.GetEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.ToolChoiceEnum>(); } },
                { "top_p", n => { TopP = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_top_p>(global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_top_p.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_frequency_penalty>("frequency_penalty", FrequencyPenalty);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_max_tokens>("max_tokens", MaxTokens);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.Prediction>("prediction", Prediction);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_presence_penalty>("presence_penalty", PresencePenalty);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_random_seed>("random_seed", RandomSeed);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_reasoning_effort>("reasoning_effort", ReasoningEffort);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ResponseFormat>("response_format", ResponseFormat);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgsStop>("stop", Stop);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_temperature>("temperature", Temperature);
            writer.WriteEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.ToolChoiceEnum>("tool_choice", ToolChoice);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_top_p>("top_p", TopP);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_frequency_penaltyMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CompletionArgs_frequency_penalty : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_frequency_penaltyMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_frequency_penaltyMember1? CompletionArgsFrequencyPenaltyMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_frequency_penaltyMember1 CompletionArgsFrequencyPenaltyMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_frequency_penalty"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_frequency_penalty CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_frequency_penalty();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else {
                    result.CompletionArgsFrequencyPenaltyMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_frequency_penaltyMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CompletionArgsFrequencyPenaltyMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CompletionArgsFrequencyPenaltyMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_frequency_penaltyMember1>(null, CompletionArgsFrequencyPenaltyMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_max_tokensMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CompletionArgs_max_tokens : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_max_tokensMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_max_tokensMember1? CompletionArgsMaxTokensMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_max_tokensMember1 CompletionArgsMaxTokensMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_max_tokens"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_max_tokens CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_max_tokens();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.CompletionArgsMaxTokensMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_max_tokensMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CompletionArgsMaxTokensMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CompletionArgsMaxTokensMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_max_tokensMember1>(null, CompletionArgsMaxTokensMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_presence_penaltyMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CompletionArgs_presence_penalty : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_presence_penaltyMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_presence_penaltyMember1? CompletionArgsPresencePenaltyMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_presence_penaltyMember1 CompletionArgsPresencePenaltyMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_presence_penalty"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_presence_penalty CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_presence_penalty();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else {
                    result.CompletionArgsPresencePenaltyMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_presence_penaltyMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CompletionArgsPresencePenaltyMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CompletionArgsPresencePenaltyMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_presence_penaltyMember1>(null, CompletionArgsPresencePenaltyMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_random_seedMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CompletionArgs_random_seed : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_random_seedMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_random_seedMember1? CompletionArgsRandomSeedMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_random_seedMember1 CompletionArgsRandomSeedMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_random_seed"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_random_seed CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_random_seed();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.CompletionArgsRandomSeedMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_random_seedMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CompletionArgsRandomSeedMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CompletionArgsRandomSeedMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_random_seedMember1>(null, CompletionArgsRandomSeedMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_reasoning_effortMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CompletionArgs_reasoning_effort : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_reasoning_effortMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_reasoning_effortMember1? CompletionArgsReasoningEffortMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_reasoning_effortMember1 CompletionArgsReasoningEffortMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_reasoning_effort"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_reasoning_effort CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_reasoning_effort();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.CompletionArgsReasoningEffortMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_reasoning_effortMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CompletionArgsReasoningEffortMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CompletionArgsReasoningEffortMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_reasoning_effortMember1>(null, CompletionArgsReasoningEffortMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_temperatureMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CompletionArgs_temperature : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_temperatureMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_temperatureMember1? CompletionArgsTemperatureMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_temperatureMember1 CompletionArgsTemperatureMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_temperature"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_temperature CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_temperature();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else {
                    result.CompletionArgsTemperatureMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_temperatureMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CompletionArgsTemperatureMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CompletionArgsTemperatureMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_temperatureMember1>(null, CompletionArgsTemperatureMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="double"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_top_pMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CompletionArgs_top_p : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_top_pMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_top_pMember1? CompletionArgsTopPMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_top_pMember1 CompletionArgsTopPMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_top_p"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_top_p CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs.CompletionArgs_top_p();
                if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else {
                    result.CompletionArgsTopPMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_top_pMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CompletionArgsTopPMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CompletionArgsTopPMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionArgs_top_pMember1>(null, CompletionArgsTopPMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
