// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConnectorMcpUpdate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>New authentication data for your mcp connector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateAuthData? AuthData { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateAuthData AuthData { get; set; }
#endif
        /// <summary>Optional new connection config.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateConnectionConfig? ConnectionConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateConnectionConfig ConnectionConfig { get; set; }
#endif
        /// <summary>Optional new connection secrets</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateConnectionSecrets? ConnectionSecrets { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateConnectionSecrets ConnectionSecrets { get; set; }
#endif
        /// <summary>The description of the connector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateDescription? Description { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateDescription Description { get; set; }
#endif
        /// <summary>New headers for your mcp connector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateHeaders? Headers { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateHeaders Headers { get; set; }
#endif
        /// <summary>The optional url of the icon you want to associate to the connector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateIconUrl? IconUrl { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateIconUrl IconUrl { get; set; }
#endif
        /// <summary>The name of the connector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateName? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateName Name { get; set; }
#endif
        /// <summary>New server url for your mcp connector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateServer? Server { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateServer Server { get; set; }
#endif
        /// <summary>Optional system prompt for the connector.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateSystemPrompt? SystemPrompt { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateSystemPrompt SystemPrompt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdate"/> and sets the default values.
        /// </summary>
        public ConnectorMcpUpdate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "auth_data", n => { AuthData = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateAuthData>(global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateAuthData.CreateFromDiscriminatorValue); } },
                { "connection_config", n => { ConnectionConfig = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateConnectionConfig>(global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateConnectionConfig.CreateFromDiscriminatorValue); } },
                { "connection_secrets", n => { ConnectionSecrets = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateConnectionSecrets>(global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateConnectionSecrets.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateDescription>(global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateDescription.CreateFromDiscriminatorValue); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateHeaders>(global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateHeaders.CreateFromDiscriminatorValue); } },
                { "icon_url", n => { IconUrl = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateIconUrl>(global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateIconUrl.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateName>(global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateName.CreateFromDiscriminatorValue); } },
                { "server", n => { Server = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateServer>(global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateServer.CreateFromDiscriminatorValue); } },
                { "system_prompt", n => { SystemPrompt = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateSystemPrompt>(global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateSystemPrompt.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateAuthData>("auth_data", AuthData);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateConnectionConfig>("connection_config", ConnectionConfig);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateConnectionSecrets>("connection_secrets", ConnectionSecrets);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateDescription>("description", Description);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateHeaders>("headers", Headers);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateIconUrl>("icon_url", IconUrl);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateName>("name", Name);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateServer>("server", Server);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConnectorMcpUpdateSystemPrompt>("system_prompt", SystemPrompt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
