// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    /// <summary>
    /// The response after appending new entries to the conversation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConversationResponse : IParsable
    {
        /// <summary>The conversation_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationId { get; set; }
#nullable restore
#else
        public string ConversationId { get; set; }
#endif
        /// <summary>The guardrails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponseGuardrails? Guardrails { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponseGuardrails Guardrails { get; set; }
#endif
        /// <summary>The object property</summary>
        public global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponse_object? Object { get; set; }
        /// <summary>The outputs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponseOutputsItem>? Outputs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponseOutputsItem> Outputs { get; set; }
#endif
        /// <summary>The usage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ConversationUsageInfo? Usage { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ConversationUsageInfo Usage { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "conversation_id", n => { ConversationId = n.GetStringValue(); } },
                { "guardrails", n => { Guardrails = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponseGuardrails>(global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponseGuardrails.CreateFromDiscriminatorValue); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponse_object>(); } },
                { "outputs", n => { Outputs = n.GetCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponseOutputsItem>(global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponseOutputsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "usage", n => { Usage = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConversationUsageInfo>(global::Soenneker.Mistral.OpenApiClient.Models.ConversationUsageInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("conversation_id", ConversationId);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponseGuardrails>("guardrails", Guardrails);
            writer.WriteEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponse_object>("object", Object);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.ConversationResponseOutputsItem>("outputs", Outputs);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConversationUsageInfo>("usage", Usage);
        }
    }
}
#pragma warning restore CS0618
