// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DatasetRecord : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The dataset_id property</summary>
        public Guid? DatasetId { get; set; }
        /// <summary>The deleted_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecordDeletedAt? DeletedAt { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecordDeletedAt DeletedAt { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The payload property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ConversationPayload? Payload { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ConversationPayload Payload { get; set; }
#endif
        /// <summary>The properties property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecordPropertiesProperty? Properties { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecordPropertiesProperty Properties { get; set; }
#endif
        /// <summary>The source property</summary>
        public global::Soenneker.Mistral.OpenApiClient.Models.ConversationSource? Source { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecord"/> and sets the default values.
        /// </summary>
        public DatasetRecord()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecord"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecord CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecord();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "dataset_id", n => { DatasetId = n.GetGuidValue(); } },
                { "deleted_at", n => { DeletedAt = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecordDeletedAt>(global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecordDeletedAt.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "payload", n => { Payload = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConversationPayload>(global::Soenneker.Mistral.OpenApiClient.Models.ConversationPayload.CreateFromDiscriminatorValue); } },
                { "properties", n => { Properties = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecordPropertiesProperty>(global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecordPropertiesProperty.CreateFromDiscriminatorValue); } },
                { "source", n => { Source = n.GetEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.ConversationSource>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteGuidValue("dataset_id", DatasetId);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecordDeletedAt>("deleted_at", DeletedAt);
            writer.WriteGuidValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ConversationPayload>("payload", Payload);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.DatasetRecordPropertiesProperty>("properties", Properties);
            writer.WriteEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.ConversationSource>("source", Source);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
