// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DocumentUrlChunk : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The filename of the document</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentName { get; set; }
#nullable restore
#else
        public string DocumentName { get; set; }
#endif
        /// <summary>The document_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentUrl { get; set; }
#nullable restore
#else
        public string DocumentUrl { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Mistral.OpenApiClient.Models.DocumentUrlChunk_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.DocumentUrlChunk"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.DocumentUrlChunk CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.DocumentUrlChunk();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "document_name", n => { DocumentName = n.GetStringValue(); } },
                { "document_url", n => { DocumentUrl = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.DocumentUrlChunk_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("document_name", DocumentName);
            writer.WriteStringValue("document_url", DocumentUrl);
            writer.WriteEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.DocumentUrlChunk_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
