// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EmbeddingRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The encoding_format property</summary>
        public global::Soenneker.Mistral.OpenApiClient.Models.EncodingFormat? EncodingFormat { get; set; }
        /// <summary>Text to embed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequestInput? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequestInput Input { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequestMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequestMetadata Metadata { get; set; }
#endif
        /// <summary>ID of the model to use.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The dimension of the output embeddings when feature available. If not provided, a default output dimension will be used.</summary>
        public int? OutputDimension { get; set; }
        /// <summary>The output_dtype property</summary>
        public global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingDtype? OutputDtype { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "encoding_format", n => { EncodingFormat = n.GetEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.EncodingFormat>(); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequestInput>(global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequestInput.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequestMetadata>(global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequestMetadata.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "output_dimension", n => { OutputDimension = n.GetIntValue(); } },
                { "output_dtype", n => { OutputDtype = n.GetEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingDtype>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.EncodingFormat>("encoding_format", EncodingFormat);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequestInput>("input", Input);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingRequestMetadata>("metadata", Metadata);
            writer.WriteStringValue("model", Model);
            writer.WriteIntValue("output_dimension", OutputDimension);
            writer.WriteEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.EmbeddingDtype>("output_dtype", OutputDtype);
        }
    }
}
#pragma warning restore CS0618
