// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ClassifierJobOut"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionJobOut"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JobsOutDataItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ClassifierJobOut"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ClassifierJobOut? ClassifierJobOut { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ClassifierJobOut ClassifierJobOut { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionJobOut"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionJobOut? CompletionJobOut { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionJobOut CompletionJobOut { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.JobsOutDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.JobsOutDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("job_type")?.GetStringValue();
            var result = new global::Soenneker.Mistral.OpenApiClient.Models.JobsOutDataItem();
            if("classifier".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ClassifierJobOut = new global::Soenneker.Mistral.OpenApiClient.Models.ClassifierJobOut();
            }
            else if("completion".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CompletionJobOut = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionJobOut();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ClassifierJobOut != null)
            {
                return ClassifierJobOut.GetFieldDeserializers();
            }
            else if(CompletionJobOut != null)
            {
                return CompletionJobOut.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ClassifierJobOut != null)
            {
                writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ClassifierJobOut>(null, ClassifierJobOut);
            }
            else if(CompletionJobOut != null)
            {
                writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionJobOut>(null, CompletionJobOut);
            }
        }
    }
}
#pragma warning restore CS0618
