// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ClassifierDetailedJobOut"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionDetailedJobOut"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JobsApiRoutesFineTuningCancelFineTuningJob200Response : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ClassifierDetailedJobOut"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ClassifierDetailedJobOut? ClassifierDetailedJobOut { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ClassifierDetailedJobOut ClassifierDetailedJobOut { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CompletionDetailedJobOut"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionDetailedJobOut? CompletionDetailedJobOut { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.CompletionDetailedJobOut CompletionDetailedJobOut { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.JobsApiRoutesFineTuningCancelFineTuningJob200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.JobsApiRoutesFineTuningCancelFineTuningJob200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("job_type")?.GetStringValue();
            var result = new global::Soenneker.Mistral.OpenApiClient.Models.JobsApiRoutesFineTuningCancelFineTuningJob200Response();
            if("classifier".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ClassifierDetailedJobOut = new global::Soenneker.Mistral.OpenApiClient.Models.ClassifierDetailedJobOut();
            }
            else if("completion".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CompletionDetailedJobOut = new global::Soenneker.Mistral.OpenApiClient.Models.CompletionDetailedJobOut();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ClassifierDetailedJobOut != null)
            {
                return ClassifierDetailedJobOut.GetFieldDeserializers();
            }
            else if(CompletionDetailedJobOut != null)
            {
                return CompletionDetailedJobOut.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ClassifierDetailedJobOut != null)
            {
                writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ClassifierDetailedJobOut>(null, ClassifierDetailedJobOut);
            }
            else if(CompletionDetailedJobOut != null)
            {
                writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CompletionDetailedJobOut>(null, CompletionDetailedJobOut);
            }
        }
    }
}
#pragma warning restore CS0618
