// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    /// <summary>Add operation </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum JsonPatchAdd_op
    {
        [EnumMember(Value = "add")]
        #pragma warning disable CS1591
        Add,
        #pragma warning restore CS1591
    }
}
