// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListWorkflowEventResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of workflow events.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_events>? Events { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_events> Events { get; set; }
#endif
        /// <summary>Cursor for pagination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_next_cursor? NextCursor { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_next_cursor NextCursor { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse"/> and sets the default values.
        /// </summary>
        public ListWorkflowEventResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "events", n => { Events = n.GetCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_events>(global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_events.CreateFromDiscriminatorValue)?.AsList(); } },
                { "next_cursor", n => { NextCursor = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_next_cursor>(global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_next_cursor.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_events>("events", Events);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_next_cursor>("next_cursor", NextCursor);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskCompletedResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskFailedResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskRetryingResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskStartedResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskCanceledResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskCompletedResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskFailedResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskInProgressResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskStartedResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskTimedOutResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionCanceledResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionCompletedResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionContinuedAsNewResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionFailedResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionStartedResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowTaskFailedResponse"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowTaskTimedOutResponse"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListWorkflowEventResponse_events : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskCompletedResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskCompletedResponse? ActivityTaskCompletedResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskCompletedResponse ActivityTaskCompletedResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskFailedResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskFailedResponse? ActivityTaskFailedResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskFailedResponse ActivityTaskFailedResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskRetryingResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskRetryingResponse? ActivityTaskRetryingResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskRetryingResponse ActivityTaskRetryingResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskStartedResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskStartedResponse? ActivityTaskStartedResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskStartedResponse ActivityTaskStartedResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskCanceledResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskCanceledResponse? CustomTaskCanceledResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskCanceledResponse CustomTaskCanceledResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskCompletedResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskCompletedResponse? CustomTaskCompletedResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskCompletedResponse CustomTaskCompletedResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskFailedResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskFailedResponse? CustomTaskFailedResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskFailedResponse CustomTaskFailedResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskInProgressResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskInProgressResponse? CustomTaskInProgressResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskInProgressResponse CustomTaskInProgressResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskStartedResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskStartedResponse? CustomTaskStartedResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskStartedResponse CustomTaskStartedResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskTimedOutResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskTimedOutResponse? CustomTaskTimedOutResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskTimedOutResponse CustomTaskTimedOutResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionCanceledResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionCanceledResponse? WorkflowExecutionCanceledResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionCanceledResponse WorkflowExecutionCanceledResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionCompletedResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionCompletedResponse? WorkflowExecutionCompletedResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionCompletedResponse WorkflowExecutionCompletedResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionContinuedAsNewResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionContinuedAsNewResponse? WorkflowExecutionContinuedAsNewResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionContinuedAsNewResponse WorkflowExecutionContinuedAsNewResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionFailedResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionFailedResponse? WorkflowExecutionFailedResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionFailedResponse WorkflowExecutionFailedResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionStartedResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionStartedResponse? WorkflowExecutionStartedResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionStartedResponse WorkflowExecutionStartedResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowTaskFailedResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowTaskFailedResponse? WorkflowTaskFailedResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowTaskFailedResponse WorkflowTaskFailedResponse { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowTaskTimedOutResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowTaskTimedOutResponse? WorkflowTaskTimedOutResponse { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowTaskTimedOutResponse WorkflowTaskTimedOutResponse { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_events"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_events CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_events();
                if("ActivityTaskCompletedResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ActivityTaskCompletedResponse = new global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskCompletedResponse();
                }
                else if("ActivityTaskFailedResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ActivityTaskFailedResponse = new global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskFailedResponse();
                }
                else if("ActivityTaskRetryingResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ActivityTaskRetryingResponse = new global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskRetryingResponse();
                }
                else if("ActivityTaskStartedResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ActivityTaskStartedResponse = new global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskStartedResponse();
                }
                else if("CustomTaskCanceledResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CustomTaskCanceledResponse = new global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskCanceledResponse();
                }
                else if("CustomTaskCompletedResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CustomTaskCompletedResponse = new global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskCompletedResponse();
                }
                else if("CustomTaskFailedResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CustomTaskFailedResponse = new global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskFailedResponse();
                }
                else if("CustomTaskInProgressResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CustomTaskInProgressResponse = new global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskInProgressResponse();
                }
                else if("CustomTaskStartedResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CustomTaskStartedResponse = new global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskStartedResponse();
                }
                else if("CustomTaskTimedOutResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CustomTaskTimedOutResponse = new global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskTimedOutResponse();
                }
                else if("WorkflowExecutionCanceledResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WorkflowExecutionCanceledResponse = new global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionCanceledResponse();
                }
                else if("WorkflowExecutionCompletedResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WorkflowExecutionCompletedResponse = new global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionCompletedResponse();
                }
                else if("WorkflowExecutionContinuedAsNewResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WorkflowExecutionContinuedAsNewResponse = new global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionContinuedAsNewResponse();
                }
                else if("WorkflowExecutionFailedResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WorkflowExecutionFailedResponse = new global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionFailedResponse();
                }
                else if("WorkflowExecutionStartedResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WorkflowExecutionStartedResponse = new global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionStartedResponse();
                }
                else if("WorkflowTaskFailedResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WorkflowTaskFailedResponse = new global::Soenneker.Mistral.OpenApiClient.Models.WorkflowTaskFailedResponse();
                }
                else if("WorkflowTaskTimedOutResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WorkflowTaskTimedOutResponse = new global::Soenneker.Mistral.OpenApiClient.Models.WorkflowTaskTimedOutResponse();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ActivityTaskCompletedResponse != null)
                {
                    return ActivityTaskCompletedResponse.GetFieldDeserializers();
                }
                else if(ActivityTaskFailedResponse != null)
                {
                    return ActivityTaskFailedResponse.GetFieldDeserializers();
                }
                else if(ActivityTaskRetryingResponse != null)
                {
                    return ActivityTaskRetryingResponse.GetFieldDeserializers();
                }
                else if(ActivityTaskStartedResponse != null)
                {
                    return ActivityTaskStartedResponse.GetFieldDeserializers();
                }
                else if(CustomTaskCanceledResponse != null)
                {
                    return CustomTaskCanceledResponse.GetFieldDeserializers();
                }
                else if(CustomTaskCompletedResponse != null)
                {
                    return CustomTaskCompletedResponse.GetFieldDeserializers();
                }
                else if(CustomTaskFailedResponse != null)
                {
                    return CustomTaskFailedResponse.GetFieldDeserializers();
                }
                else if(CustomTaskInProgressResponse != null)
                {
                    return CustomTaskInProgressResponse.GetFieldDeserializers();
                }
                else if(CustomTaskStartedResponse != null)
                {
                    return CustomTaskStartedResponse.GetFieldDeserializers();
                }
                else if(CustomTaskTimedOutResponse != null)
                {
                    return CustomTaskTimedOutResponse.GetFieldDeserializers();
                }
                else if(WorkflowExecutionCanceledResponse != null)
                {
                    return WorkflowExecutionCanceledResponse.GetFieldDeserializers();
                }
                else if(WorkflowExecutionCompletedResponse != null)
                {
                    return WorkflowExecutionCompletedResponse.GetFieldDeserializers();
                }
                else if(WorkflowExecutionContinuedAsNewResponse != null)
                {
                    return WorkflowExecutionContinuedAsNewResponse.GetFieldDeserializers();
                }
                else if(WorkflowExecutionFailedResponse != null)
                {
                    return WorkflowExecutionFailedResponse.GetFieldDeserializers();
                }
                else if(WorkflowExecutionStartedResponse != null)
                {
                    return WorkflowExecutionStartedResponse.GetFieldDeserializers();
                }
                else if(WorkflowTaskFailedResponse != null)
                {
                    return WorkflowTaskFailedResponse.GetFieldDeserializers();
                }
                else if(WorkflowTaskTimedOutResponse != null)
                {
                    return WorkflowTaskTimedOutResponse.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ActivityTaskCompletedResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskCompletedResponse>(null, ActivityTaskCompletedResponse);
                }
                else if(ActivityTaskFailedResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskFailedResponse>(null, ActivityTaskFailedResponse);
                }
                else if(ActivityTaskRetryingResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskRetryingResponse>(null, ActivityTaskRetryingResponse);
                }
                else if(ActivityTaskStartedResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ActivityTaskStartedResponse>(null, ActivityTaskStartedResponse);
                }
                else if(CustomTaskCanceledResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskCanceledResponse>(null, CustomTaskCanceledResponse);
                }
                else if(CustomTaskCompletedResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskCompletedResponse>(null, CustomTaskCompletedResponse);
                }
                else if(CustomTaskFailedResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskFailedResponse>(null, CustomTaskFailedResponse);
                }
                else if(CustomTaskInProgressResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskInProgressResponse>(null, CustomTaskInProgressResponse);
                }
                else if(CustomTaskStartedResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskStartedResponse>(null, CustomTaskStartedResponse);
                }
                else if(CustomTaskTimedOutResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.CustomTaskTimedOutResponse>(null, CustomTaskTimedOutResponse);
                }
                else if(WorkflowExecutionCanceledResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionCanceledResponse>(null, WorkflowExecutionCanceledResponse);
                }
                else if(WorkflowExecutionCompletedResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionCompletedResponse>(null, WorkflowExecutionCompletedResponse);
                }
                else if(WorkflowExecutionContinuedAsNewResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionContinuedAsNewResponse>(null, WorkflowExecutionContinuedAsNewResponse);
                }
                else if(WorkflowExecutionFailedResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionFailedResponse>(null, WorkflowExecutionFailedResponse);
                }
                else if(WorkflowExecutionStartedResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionStartedResponse>(null, WorkflowExecutionStartedResponse);
                }
                else if(WorkflowTaskFailedResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowTaskFailedResponse>(null, WorkflowTaskFailedResponse);
                }
                else if(WorkflowTaskTimedOutResponse != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowTaskTimedOutResponse>(null, WorkflowTaskTimedOutResponse);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse_next_cursorMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListWorkflowEventResponse_next_cursor : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse_next_cursorMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse_next_cursorMember1? ListWorkflowEventResponseNextCursorMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse_next_cursorMember1 ListWorkflowEventResponseNextCursorMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_next_cursor"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_next_cursor CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse.ListWorkflowEventResponse_next_cursor();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ListWorkflowEventResponseNextCursorMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse_next_cursorMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ListWorkflowEventResponseNextCursorMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ListWorkflowEventResponseNextCursorMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ListWorkflowEventResponse_next_cursorMember1>(null, ListWorkflowEventResponseNextCursorMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
