// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MessageOutputEntry_object
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "entry")]
        #pragma warning disable CS1591
        Entry,
        #pragma warning restore CS1591
    }
}
