// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OCRImageObject : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>X coordinate of bottom-right corner of the extracted image</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_x? BottomRightX { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_x BottomRightX { get; set; }
#endif
        /// <summary>Y coordinate of bottom-right corner of the extracted image</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_y? BottomRightY { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_y BottomRightY { get; set; }
#endif
        /// <summary>Image ID for extracted image in a page</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Annotation of the extracted image in json str</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_annotation? ImageAnnotation { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_annotation ImageAnnotation { get; set; }
#endif
        /// <summary>Base64 string of the extracted image</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_base64? ImageBase64 { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_base64 ImageBase64 { get; set; }
#endif
        /// <summary>X coordinate of top-left corner of the extracted image</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_x? TopLeftX { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_x TopLeftX { get; set; }
#endif
        /// <summary>Y coordinate of top-left corner of the extracted image</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_y? TopLeftY { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_y TopLeftY { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bottom_right_x", n => { BottomRightX = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_x>(global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_x.CreateFromDiscriminatorValue); } },
                { "bottom_right_y", n => { BottomRightY = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_y>(global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_y.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "image_annotation", n => { ImageAnnotation = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_annotation>(global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_annotation.CreateFromDiscriminatorValue); } },
                { "image_base64", n => { ImageBase64 = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_base64>(global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_base64.CreateFromDiscriminatorValue); } },
                { "top_left_x", n => { TopLeftX = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_x>(global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_x.CreateFromDiscriminatorValue); } },
                { "top_left_y", n => { TopLeftY = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_y>(global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_y.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_x>("bottom_right_x", BottomRightX);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_y>("bottom_right_y", BottomRightY);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_annotation>("image_annotation", ImageAnnotation);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_base64>("image_base64", ImageBase64);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_x>("top_left_x", TopLeftX);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_y>("top_left_y", TopLeftY);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_bottom_right_xMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OCRImageObject_bottom_right_x : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_bottom_right_xMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_bottom_right_xMember1? OCRImageObjectBottomRightXMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_bottom_right_xMember1 OCRImageObjectBottomRightXMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_x"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_x CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_x();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.OCRImageObjectBottomRightXMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_bottom_right_xMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OCRImageObjectBottomRightXMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OCRImageObjectBottomRightXMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_bottom_right_xMember1>(null, OCRImageObjectBottomRightXMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_bottom_right_yMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OCRImageObject_bottom_right_y : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_bottom_right_yMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_bottom_right_yMember1? OCRImageObjectBottomRightYMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_bottom_right_yMember1 OCRImageObjectBottomRightYMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_y"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_y CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_bottom_right_y();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.OCRImageObjectBottomRightYMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_bottom_right_yMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OCRImageObjectBottomRightYMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OCRImageObjectBottomRightYMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_bottom_right_yMember1>(null, OCRImageObjectBottomRightYMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_image_annotationMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OCRImageObject_image_annotation : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_image_annotationMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_image_annotationMember1? OCRImageObjectImageAnnotationMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_image_annotationMember1 OCRImageObjectImageAnnotationMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_annotation"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_annotation CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_annotation();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.OCRImageObjectImageAnnotationMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_image_annotationMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OCRImageObjectImageAnnotationMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OCRImageObjectImageAnnotationMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_image_annotationMember1>(null, OCRImageObjectImageAnnotationMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_image_base64Member1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OCRImageObject_image_base64 : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_image_base64Member1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_image_base64Member1? OCRImageObjectImageBase64Member1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_image_base64Member1 OCRImageObjectImageBase64Member1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_base64"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_base64 CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_image_base64();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.OCRImageObjectImageBase64Member1 = new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_image_base64Member1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OCRImageObjectImageBase64Member1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OCRImageObjectImageBase64Member1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_image_base64Member1>(null, OCRImageObjectImageBase64Member1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_top_left_xMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OCRImageObject_top_left_x : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_top_left_xMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_top_left_xMember1? OCRImageObjectTopLeftXMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_top_left_xMember1 OCRImageObjectTopLeftXMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_x"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_x CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_x();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.OCRImageObjectTopLeftXMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_top_left_xMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OCRImageObjectTopLeftXMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OCRImageObjectTopLeftXMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_top_left_xMember1>(null, OCRImageObjectTopLeftXMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_top_left_yMember1"/>, <see cref="int"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OCRImageObject_top_left_y : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_top_left_yMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_top_left_yMember1? OCRImageObjectTopLeftYMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_top_left_yMember1 OCRImageObjectTopLeftYMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_y"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_y CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject.OCRImageObject_top_left_y();
                if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else {
                    result.OCRImageObjectTopLeftYMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_top_left_yMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OCRImageObjectTopLeftYMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(OCRImageObjectTopLeftYMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.OCRImageObject_top_left_yMember1>(null, OCRImageObjectTopLeftYMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
