// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    /// <summary>
    /// Specification of the times scheduled actions may occur.The times are the union of :py:attr:`calendars`, :py:attr:`intervals`, and:py:attr:`cron_expressions` excluding anything in :py:attr:`skip`.Used for input where schedule_id is optional (can be provided or auto-generated).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ScheduleDefinition : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Calendar-based specification of times.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleCalendar>? Calendars { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleCalendar> Calendars { get; set; }
#endif
        /// <summary>Cron-based specification of times.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CronExpressions { get; set; }
#nullable restore
#else
        public List<string> CronExpressions { get; set; }
#endif
        /// <summary>Time after which no more actions will be run.</summary>
        public DateTimeOffset? EndAt { get; set; }
        /// <summary>Input to provide to the workflow when starting it.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.ScheduleDefinitionInput? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.ScheduleDefinitionInput Input { get; set; }
#endif
        /// <summary>Interval-based specification of times.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleInterval>? Intervals { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleInterval> Intervals { get; set; }
#endif
        /// <summary>Jitter to apply each action.An action&apos;s scheduled time will be incremented by a random value between 0and this value if present (but not past the next schedule).</summary>
        public TimeSpan? Jitter { get; set; }
        /// <summary>The policy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.SchedulePolicy? Policy { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.SchedulePolicy Policy { get; set; }
#endif
        /// <summary>Unique identifier for the schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScheduleId { get; set; }
#nullable restore
#else
        public string ScheduleId { get; set; }
#endif
        /// <summary>Set of calendar times to skip.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleCalendar>? Skip { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleCalendar> Skip { get; set; }
#endif
        /// <summary>Time after which the first action may be run.</summary>
        public DateTimeOffset? StartAt { get; set; }
        /// <summary>IANA time zone name, for example ``US/Central``.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZoneName { get; set; }
#nullable restore
#else
        public string TimeZoneName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ScheduleDefinition"/> and sets the default values.
        /// </summary>
        public ScheduleDefinition()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.ScheduleDefinition"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.ScheduleDefinition CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.ScheduleDefinition();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calendars", n => { Calendars = n.GetCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleCalendar>(global::Soenneker.Mistral.OpenApiClient.Models.ScheduleCalendar.CreateFromDiscriminatorValue)?.AsList(); } },
                { "cron_expressions", n => { CronExpressions = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "end_at", n => { EndAt = n.GetDateTimeOffsetValue(); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleDefinitionInput>(global::Soenneker.Mistral.OpenApiClient.Models.ScheduleDefinitionInput.CreateFromDiscriminatorValue); } },
                { "intervals", n => { Intervals = n.GetCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleInterval>(global::Soenneker.Mistral.OpenApiClient.Models.ScheduleInterval.CreateFromDiscriminatorValue)?.AsList(); } },
                { "jitter", n => { Jitter = n.GetTimeSpanValue(); } },
                { "policy", n => { Policy = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SchedulePolicy>(global::Soenneker.Mistral.OpenApiClient.Models.SchedulePolicy.CreateFromDiscriminatorValue); } },
                { "schedule_id", n => { ScheduleId = n.GetStringValue(); } },
                { "skip", n => { Skip = n.GetCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleCalendar>(global::Soenneker.Mistral.OpenApiClient.Models.ScheduleCalendar.CreateFromDiscriminatorValue)?.AsList(); } },
                { "start_at", n => { StartAt = n.GetDateTimeOffsetValue(); } },
                { "time_zone_name", n => { TimeZoneName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleCalendar>("calendars", Calendars);
            writer.WriteCollectionOfPrimitiveValues<string>("cron_expressions", CronExpressions);
            writer.WriteDateTimeOffsetValue("end_at", EndAt);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleDefinitionInput>("input", Input);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleInterval>("intervals", Intervals);
            writer.WriteTimeSpanValue("jitter", Jitter);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SchedulePolicy>("policy", Policy);
            writer.WriteStringValue("schedule_id", ScheduleId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.ScheduleCalendar>("skip", Skip);
            writer.WriteDateTimeOffsetValue("start_at", StartAt);
            writer.WriteStringValue("time_zone_name", TimeZoneName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
