// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SharingDelete : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The org_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete.SharingDelete_org_id? OrgId { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete.SharingDelete_org_id OrgId { get; set; }
#endif
        /// <summary>The type of entity, used to share a library.</summary>
        public global::Soenneker.Mistral.OpenApiClient.Models.EntityType? ShareWithType { get; set; }
        /// <summary>The id of the entity (user, workspace or organization) to share with</summary>
        public Guid? ShareWithUuid { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete"/> and sets the default values.
        /// </summary>
        public SharingDelete()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "org_id", n => { OrgId = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete.SharingDelete_org_id>(global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete.SharingDelete_org_id.CreateFromDiscriminatorValue); } },
                { "share_with_type", n => { ShareWithType = n.GetEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.EntityType>(); } },
                { "share_with_uuid", n => { ShareWithUuid = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete.SharingDelete_org_id>("org_id", OrgId);
            writer.WriteEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.EntityType>("share_with_type", ShareWithType);
            writer.WriteGuidValue("share_with_uuid", ShareWithUuid);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete_org_idMember1"/>, <see cref="Guid"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SharingDelete_org_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="Guid"/></summary>
            public Guid? Guid { get; set; }
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete_org_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete_org_idMember1? SharingDeleteOrgIdMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete_org_idMember1 SharingDeleteOrgIdMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete.SharingDelete_org_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete.SharingDelete_org_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete.SharingDelete_org_id();
                if(parseNode.GetGuidValue() is Guid guidValue)
                {
                    result.Guid = guidValue;
                }
                else {
                    result.SharingDeleteOrgIdMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete_org_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(SharingDeleteOrgIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(SharingDeleteOrgIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Guid != null)
                {
                    writer.WriteGuidValue(null, Guid);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SharingDelete_org_idMember1>(null, SharingDeleteOrgIdMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
