// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SpeechRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Text to generate speech from.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Input { get; set; }
#nullable restore
#else
        public string Input { get; set; }
#endif
        /// <summary>The model property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_model? Model { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_model Model { get; set; }
#endif
        /// <summary>The base64-encoded audio reference for zero-shot voice cloning.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_ref_audio? RefAudio { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_ref_audio RefAudio { get; set; }
#endif
        /// <summary>Output audio format. Defaults to mp3.</summary>
        public global::Soenneker.Mistral.OpenApiClient.Models.SpeechOutputFormat? ResponseFormat { get; set; }
        /// <summary>The stream property</summary>
        public bool? Stream { get; set; }
        /// <summary>The preset or custom voice to use for generating the speech.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_voice_id? VoiceId { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_voice_id VoiceId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest"/> and sets the default values.
        /// </summary>
        public SpeechRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            ResponseFormat = global::Soenneker.Mistral.OpenApiClient.Models.SpeechOutputFormat.Mp3;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "input", n => { Input = n.GetStringValue(); } },
                { "model", n => { Model = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_model>(global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_model.CreateFromDiscriminatorValue); } },
                { "ref_audio", n => { RefAudio = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_ref_audio>(global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_ref_audio.CreateFromDiscriminatorValue); } },
                { "response_format", n => { ResponseFormat = n.GetEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.SpeechOutputFormat>(); } },
                { "stream", n => { Stream = n.GetBoolValue(); } },
                { "voice_id", n => { VoiceId = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_voice_id>(global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_voice_id.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("input", Input);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_model>("model", Model);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_ref_audio>("ref_audio", RefAudio);
            writer.WriteEnumValue<global::Soenneker.Mistral.OpenApiClient.Models.SpeechOutputFormat>("response_format", ResponseFormat);
            writer.WriteBoolValue("stream", Stream);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_voice_id>("voice_id", VoiceId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_modelMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SpeechRequest_model : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_modelMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_modelMember1? SpeechRequestModelMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_modelMember1 SpeechRequestModelMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_model"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_model CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_model();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.SpeechRequestModelMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_modelMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(SpeechRequestModelMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(SpeechRequestModelMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_modelMember1>(null, SpeechRequestModelMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_ref_audioMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SpeechRequest_ref_audio : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_ref_audioMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_ref_audioMember1? SpeechRequestRefAudioMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_ref_audioMember1 SpeechRequestRefAudioMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_ref_audio"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_ref_audio CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_ref_audio();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.SpeechRequestRefAudioMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_ref_audioMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(SpeechRequestRefAudioMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(SpeechRequestRefAudioMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_ref_audioMember1>(null, SpeechRequestRefAudioMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_voice_idMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SpeechRequest_voice_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_voice_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_voice_idMember1? SpeechRequestVoiceIdMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_voice_idMember1 SpeechRequestVoiceIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_voice_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_voice_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest.SpeechRequest_voice_id();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.SpeechRequestVoiceIdMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_voice_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(SpeechRequestVoiceIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(SpeechRequestVoiceIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.SpeechRequest_voice_idMember1>(null, SpeechRequestVoiceIdMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
