// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeBoolValue"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeIntValue"/>, <see cref="global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeStringValue"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TempoTraceAttributeValue : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeBoolValue"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeBoolValue? TempoTraceAttributeBoolValue { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeBoolValue TempoTraceAttributeBoolValue { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeIntValue"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeIntValue? TempoTraceAttributeIntValue { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeIntValue TempoTraceAttributeIntValue { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeStringValue"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeStringValue? TempoTraceAttributeStringValue { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeStringValue TempoTraceAttributeStringValue { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeValue();
            result.TempoTraceAttributeBoolValue = new global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeBoolValue();
            result.TempoTraceAttributeIntValue = new global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeIntValue();
            result.TempoTraceAttributeStringValue = new global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeStringValue();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(TempoTraceAttributeBoolValue != null || TempoTraceAttributeIntValue != null || TempoTraceAttributeStringValue != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(TempoTraceAttributeBoolValue, TempoTraceAttributeIntValue, TempoTraceAttributeStringValue);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.TempoTraceAttributeBoolValue>(null, TempoTraceAttributeBoolValue, TempoTraceAttributeIntValue, TempoTraceAttributeStringValue);
        }
    }
}
#pragma warning restore CS0618
