// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WorkflowExecutionListResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A list of workflow executions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionWithoutResultResponse>? Executions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionWithoutResultResponse> Executions { get; set; }
#endif
        /// <summary>Token to use for fetching the next page of results. Null if this is the last page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse.WorkflowExecutionListResponse_next_page_token? NextPageToken { get; set; }
#nullable restore
#else
        public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse.WorkflowExecutionListResponse_next_page_token NextPageToken { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse"/> and sets the default values.
        /// </summary>
        public WorkflowExecutionListResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "executions", n => { Executions = n.GetCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionWithoutResultResponse>(global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionWithoutResultResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "next_page_token", n => { NextPageToken = n.GetObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse.WorkflowExecutionListResponse_next_page_token>(global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse.WorkflowExecutionListResponse_next_page_token.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionWithoutResultResponse>("executions", Executions);
            writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse.WorkflowExecutionListResponse_next_page_token>("next_page_token", NextPageToken);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse_next_page_tokenMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WorkflowExecutionListResponse_next_page_token : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse_next_page_tokenMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse_next_page_tokenMember1? WorkflowExecutionListResponseNextPageTokenMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse_next_page_tokenMember1 WorkflowExecutionListResponseNextPageTokenMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse.WorkflowExecutionListResponse_next_page_token"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse.WorkflowExecutionListResponse_next_page_token CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse.WorkflowExecutionListResponse_next_page_token();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.WorkflowExecutionListResponseNextPageTokenMember1 = new global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse_next_page_tokenMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WorkflowExecutionListResponseNextPageTokenMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WorkflowExecutionListResponseNextPageTokenMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Mistral.OpenApiClient.Models.WorkflowExecutionListResponse_next_page_tokenMember1>(null, WorkflowExecutionListResponseNextPageTokenMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
