// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Mistral.OpenApiClient.Models
{
    /// <summary>Event type discriminator.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WorkflowTaskFailedResponse_event_type
    {
        [EnumMember(Value = "WORKFLOW_TASK_FAILED")]
        #pragma warning disable CS1591
        WorkflowTaskFailed,
        #pragma warning restore CS1591
    }
}
