// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mistral.OpenApiClient.V1.Connectors.Item.Tools.Item.Call;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Mistral.OpenApiClient.V1.Connectors.Item.Tools.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\connectors\{connector_id_or_name}\tools\{tool_name}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTool_nameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The call property</summary>
        public global::Soenneker.Mistral.OpenApiClient.V1.Connectors.Item.Tools.Item.Call.CallRequestBuilder Call
        {
            get => new global::Soenneker.Mistral.OpenApiClient.V1.Connectors.Item.Tools.Item.Call.CallRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.V1.Connectors.Item.Tools.Item.WithTool_nameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTool_nameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/connectors/{connector_id_or_name}/tools/{tool_name}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.V1.Connectors.Item.Tools.Item.WithTool_nameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTool_nameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/connectors/{connector_id_or_name}/tools/{tool_name}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
