// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mistral.OpenApiClient.Models;
using Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\fine_tuning\jobs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class JobsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Mistral.OpenApiClient.v1.fine_tuning.jobs.item collection</summary>
        /// <param name="position">The ID of the job to analyse.</param>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.Item.WithJob_ItemRequestBuilder"/></returns>
        public global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.Item.WithJob_ItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("job_id", position);
                return new global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.Item.WithJob_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JobsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/fine_tuning/jobs{?created_after*,created_before*,created_by_me*,dry_run*,model*,page*,page_size*,status*,suffix*,wandb_name*,wandb_project*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public JobsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/fine_tuning/jobs{?created_after*,created_before*,created_by_me*,dry_run*,model*,page*,page_size*,status*,suffix*,wandb_name*,wandb_project*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a list of fine-tuning jobs for your organization and user.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.JobsOut"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Mistral.OpenApiClient.Models.JobsOut?> GetAsync(Action<RequestConfiguration<global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder.JobsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Mistral.OpenApiClient.Models.JobsOut> GetAsync(Action<RequestConfiguration<global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder.JobsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Mistral.OpenApiClient.Models.JobsOut>(requestInfo, global::Soenneker.Mistral.OpenApiClient.Models.JobsOut.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new fine-tuning job, it will be queued for processing.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.Models.LegacyJobMetadataOut"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Mistral.OpenApiClient.Models.LegacyJobMetadataOut?> PostAsync(global::Soenneker.Mistral.OpenApiClient.Models.JobIn body, Action<RequestConfiguration<global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder.JobsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Mistral.OpenApiClient.Models.LegacyJobMetadataOut> PostAsync(global::Soenneker.Mistral.OpenApiClient.Models.JobIn body, Action<RequestConfiguration<global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder.JobsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Mistral.OpenApiClient.Models.LegacyJobMetadataOut>(requestInfo, global::Soenneker.Mistral.OpenApiClient.Models.LegacyJobMetadataOut.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a list of fine-tuning jobs for your organization and user.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder.JobsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder.JobsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a new fine-tuning job, it will be queued for processing.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Mistral.OpenApiClient.Models.JobIn body, Action<RequestConfiguration<global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder.JobsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Mistral.OpenApiClient.Models.JobIn body, Action<RequestConfiguration<global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder.JobsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Mistral.OpenApiClient.V1.Fine_tuning.Jobs.JobsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a list of fine-tuning jobs for your organization and user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class JobsRequestBuilderGetQueryParameters 
        {
            /// <summary>The date/time to filter on. When set, the results for previous creation times are not displayed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("created_after")]
            public string? CreatedAfter { get; set; }
#nullable restore
#else
            [QueryParameter("created_after")]
            public string CreatedAfter { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("created_before")]
            public string? CreatedBefore { get; set; }
#nullable restore
#else
            [QueryParameter("created_before")]
            public string CreatedBefore { get; set; }
#endif
            /// <summary>When set, only return results for jobs created by the API caller. Other results are not displayed.</summary>
            [QueryParameter("created_by_me")]
            public bool? CreatedByMe { get; set; }
            /// <summary>The model name used for fine-tuning to filter on. When set, the other results are not displayed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("model")]
            public string? Model { get; set; }
#nullable restore
#else
            [QueryParameter("model")]
            public string Model { get; set; }
#endif
            /// <summary>The page number of the results to be returned.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>The number of items to return per page.</summary>
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
            /// <summary>The current job state to filter on. When set, the other results are not displayed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
            /// <summary>The model suffix to filter on. When set, the other results are not displayed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("suffix")]
            public string? Suffix { get; set; }
#nullable restore
#else
            [QueryParameter("suffix")]
            public string Suffix { get; set; }
#endif
            /// <summary>The Weight and Biases run name to filter on. When set, the other results are not displayed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("wandb_name")]
            public string? WandbName { get; set; }
#nullable restore
#else
            [QueryParameter("wandb_name")]
            public string WandbName { get; set; }
#endif
            /// <summary>The Weights and Biases project to filter on. When set, the other results are not displayed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("wandb_project")]
            public string? WandbProject { get; set; }
#nullable restore
#else
            [QueryParameter("wandb_project")]
            public string WandbProject { get; set; }
#endif
        }
        /// <summary>
        /// Create a new fine-tuning job, it will be queued for processing.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class JobsRequestBuilderPostQueryParameters 
        {
            /// <summary>* If `true` the job is not spawned, instead the query returns a handful of useful metadata  for the user to perform sanity checks (see `LegacyJobMetadataOut` response).* Otherwise, the job is started and the query returns the job ID along with some of the  input parameters (see `JobOut` response).</summary>
            [QueryParameter("dry_run")]
            public bool? DryRun { get; set; }
        }
    }
}
#pragma warning restore CS0618
