// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Mistral.OpenApiClient.V1.Connectors.Item.Workspace.Credentials;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Mistral.OpenApiClient.V1.Connectors.Item.Workspace
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\connectors\{connectorIdOrName}\workspace
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkspaceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The credentials property</summary>
        public global::Soenneker.Mistral.OpenApiClient.V1.Connectors.Item.Workspace.Credentials.CredentialsRequestBuilder Credentials
        {
            get => new global::Soenneker.Mistral.OpenApiClient.V1.Connectors.Item.Workspace.Credentials.CredentialsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.V1.Connectors.Item.Workspace.WorkspaceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkspaceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/connectors/{connectorIdOrName}/workspace", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Mistral.OpenApiClient.V1.Connectors.Item.Workspace.WorkspaceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkspaceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/connectors/{connectorIdOrName}/workspace", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
